### ISSUE TITLE
我也遇到了同样的问题，经过一晚上鼓捣解决了

### ISSUE THREAD

**Issue by Riso-Enjinia** [xiaolaba/Luatos_EPS32_C3_C3-L_ST7735_what_a_bug#1]
我采用的是TFT_eSPI+ST7789-1.69inch TFT,同意的屏同样的库文件测试结果不同，
主要是TFT_eSPI\User_Setups\Setup203_ST7789.h中SPI引脚定义的问题
在ESP8266上采用只定义DC、RST、CS的方式即可亮屏
```c++
filename:TFT_eSPI\User_Setups\Setup203_ST7789.h
#define TFT_DC D1   // TFT DC  pin is connected to NodeMCU pin D1 (GPIO5)
#define TFT_RST D2  // TFT RST pin is connected to NodeMCU pin D2 (GPIO4)
#define TFT_CS D8   // TFT CS  pin is connected to NodeMCU pin D8 (GPIO15)
// initialize ST7789 TFT library with hardware SPI module
// SCK (CLK) ---> NodeMCU pin D5 (GPIO14)
// MOSI(DIN) ---> NodeMCU pin D7 (GPIO13)
``` 
但在ESP32C3L上却需要完整定义四线SPI全部接口，假如不定义，开发板就会无限重启（给人假象就是开发板不工作了），可以CDC_debug=disable以后用外接UART看串口信息，会提示SPI存储初始化失败，然后不断重启
修改配置如下后点屏正常
```c++
filename:TFT_eSPI\User_Setups\Setup203_ST7789.h
#define TFT_MOSI 3  //对于合宙的ESP32C3，必须固定定义
#define TFT_SCLK 2  //对于合宙的ESP32C3，必须固定定义
#define TFT_CS    7 //对于合宙的ESP32C3，可更改
#define TFT_DC    6 //对于合宙的ESP32C3，可更改
#define TFT_RST   10  //对于合宙的ESP32C3，可更改
```

**Comment by xiaolaba** [comment]
這個對 合宙的ESP32C3L (沒有USB-UART CHIP), 依然無顯示

> 我采用的是TFT_eSPI+ST7789-1.69inch TFT,同意的屏同样的库文件测试结果不同， 主要是TFT_eSPI\User_Setups\Setup203_ST7789.h中SPI引脚定义的问题 在ESP8266上采用只定义DC、RST、CS的方式即可亮屏
> 
> ```c++
> filename:TFT_eSPI\User_Setups\Setup203_ST7789.h
> #define TFT_DC D1   // TFT DC  pin is connected to NodeMCU pin D1 (GPIO5)
> #define TFT_RST D2  // TFT RST pin is connected to NodeMCU pin D2 (GPIO4)
> #define TFT_CS D8   // TFT CS  pin is connected to NodeMCU pin D8 (GPIO15)
> // initialize ST7789 TFT library with hardware SPI module
> // SCK (CLK) ---> NodeMCU pin D5 (GPIO14)
> // MOSI(DIN) ---> NodeMCU pin D7 (GPIO13)
> ```
> 
> 但在ESP32C3L上却需要完整定义四线SPI全部接口，假如不定义，开发板就会无限重启（给人假象就是开发板不工作了），可以CDC_debug=disable以后用外接UART看串口信息，会提示SPI存储初始化失败，然后不断重启 修改配置如下后点屏正常
> 
> ```c++
> filename:TFT_eSPI\User_Setups\Setup203_ST7789.h
> #define TFT_MOSI 3  //对于合宙的ESP32C3，必须固定定义
> #define TFT_SCLK 2  //对于合宙的ESP32C3，必须固定定义
> #define TFT_CS    7 //对于合宙的ESP32C3，可更改
> #define TFT_DC    6 //对于合宙的ESP32C3，可更改
> #define TFT_RST   10  //对于合宙的ESP32C3，可更改
> ```

這個對 合宙的ESP32C3L (沒有USB-UART CHIP), 依然無顯示

**Comment by xiaolaba** [comment]
V1005 does the job, looks like the bug is fixed

**Comment by xiaolaba** [comment]
link https://github.com/xiaolaba/Luatos_EPS32_C3_C3-L_ST7735_what_a_bug#2023-11-12-update-seems-bug-fixed
